# fly.toml app configuration file generated for rwalk on 2023-05-27T15:24:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rwalk"
primary_region = "cdg"

[experimental]
auto_rollback = true

[http_service]
internal_port = 8080
force_https = true
min_machines_running = 1
processes = ["app"]

[http_service.concurrency]
type = "requests"
soft_limit = 20
hard_limit = 25
