[tool.poetry]
name = "rwalk"
version = "0.0.0"
description = "dash app random walk"
authors = ["andros21 <andrea.ros21@e.email>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pandas = "^2.1.0"
numpy = "^1.25.2"
dash = "^2.13.0"
networkx = "^3.1"
gunicorn = "^21.2.0"
scipy = "^1.11.2"
dash-cytoscape = "^0.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
