[tool.poetry]
name = "rwalk"
version = "0.0.0"
description = "dash app random walk"
authors = ["andros21 <andrea.ros21@e.email>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pandas = "^1.5.3"
numpy = "^1.24.2"
dash = "^2.8.1"
networkx = "^3.0"
gunicorn = "^20.1.0"
scipy = "^1.10.0"
dash-cytoscape = "^0.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
