[tool.poetry]
name = "rwalk"
version = "0.0.0"
description = "dash app random walk"
authors = ["andros21 <andrea.ros21@e.email>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^1.5.1"
numpy = "^1.23.4"
dash = "^2.6.2"
networkx = "^2.8.8"
gunicorn = "^20.1.0"
scipy = "^1.9.3"
dash-cytoscape = "^0.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
