---
name: flyio deploy

"on":
  push:
    branches:
      - flyio

permissions:
  contents: read

jobs:
  deploy:
    name: flyio deploy
    runs-on: ubuntu-latest
    environment:
      name: flyio
      url: https://rwalk.fly.dev
    steps:
      - name: checkout project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: flyio deploy
        uses: superfly/flyctl-actions@adbb124b95f2e47566253d95497432c27f4bdd70
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
