---
name: flyio deploy

"on":
  workflow_dispatch:
  push:
    branches:
      - flyio

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: flyio deploy
    runs-on: ubuntu-latest
    environment:
      name: flyio
      url: https://rwalk.fly.dev
    steps:
      - name: checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: install cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b
      - name: verify rwalk image
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign verify "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" | jq
      - name: flyio deploy
        uses: superfly/flyctl-actions@adbb124b95f2e47566253d95497432c27f4bdd70
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
