---
name: flyio deploy

"on":
  workflow_dispatch:
  push:
    branches:
      - flyio

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: flyio deploy
    runs-on: ubuntu-latest
    environment:
      name: flyio
      url: https://rwalk.fly.dev
    steps:
      - name: checkout project
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: install cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da
      - name: verify rwalk image
        run: |
          cosign verify \
             --certificate-identity \
             'https://github.com/andros21/rwalk/.github/workflows/build.yml@refs/heads/master' \
             --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
             "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" | jq .
      - name: flyio setup
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: flyio deploy
        run: |
          flyctl deploy --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
