---
name: digesta bot

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 * *"

jobs:
  image-update:
    name: image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: chainguard-dev/digestabot@33d0b78e580aa0c83fe188eb3dfad6611b662479
        with:
          title-for-pr: 'build(Dockerfile): bump python latest tag digest'
          commit-message: 'build(Dockerfile): bump python latest tag digest'
          labels-for-pr: dependencies, docker
          token: ${{ secrets.GITHUB_TOKEN }}
